### ISSUE TITLE
Discord bot is not verified

### ISSUE THREAD

**Issue by orthon22** [MrBaggieBug/Ben-bot#1]
When it try to invite BenBot to my server, it says that it has not been verified. u need to verify it [https://dis.gd/bot-verification](url)

**Comment by Baggiest** [comment]
Hey Orthon, yes I am indeed aware of it, and I made a command "yo invite" explaining exactly why its happening, and link to a temporary alt ben

long story short, the main one will get verified in a week or 2 maximum
I'm happy to answer any other question u might have

have great day

**Comment by orthon22** [comment]
What are the commands for ben bot??


ma 28. helmik. 2022 klo 12.59 ManiTheDev ***@***.***)
kirjoitti:

**Comment by Baggiest** [comment]
It's pretty simple, "yo" is our prefix

So u can send "yo help"
Or if u want to ask anything from Ben

Just do "yo Ben [your question]"

For example "yo Ben how r u"

**Comment by orthon22** [comment]
Thanks

pe 4. maalisk. 2022 klo 22.06 ManiTheDev ***@***.***>
kirjoitti:
